swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains API endpoints for transactions
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /accounts/{account_Id}/transactions/{month}/{year}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Returns all transactions of account for a specific month and year.
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: account_Id
          required: true
          type: integer
          description: Numeric ID of the account
        - in: path
          name: month
          required: true
          type: integer
          description: Month
        - in: path
          name: year
          required: true
          type: integer
          description: Year
      produces:
        - application/json
      responses:
        '200':
          description: Transactions are successfully retrieved
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  
  /accounts/{account_Id}/transactions/{transaction_Id}/details:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Returns the details of a transaction.
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: account_Id
          required: true
          type: integer
          description: Numeric ID of the account
        - in: path
          name: transaction_Id
          required: true
          type: integer
          description: Numeric ID of the transaction
      produces:
        - application/json
      responses:
        '200':
          description: Details are successfully retrieved
          schema:
            $ref: '#/definitions/TransactionDetails'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

    post:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Add informations about a transaction.
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: account_Id
          required: true
          type: integer
          description: Numeric ID of the account
        - in: path
          name: transaction_Id
          required: true
          type: integer
          description: Numeric ID of the transaction
        - in: body
          name: body
          description: Add informations about the transaction
          required: true
          schema:
            $ref: '#/definitions/EditDetails'
      produces:
        - application/json
      responses:
        '200':
          description: Details are successfully added
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    
    put:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Edit informations about a transaction.
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: account_Id
          required: true
          type: integer
          description: Numeric ID of the account
        - in: path
          name: transaction_Id
          required: true
          type: integer
          description: Numeric ID of the transaction
        - in: body
          name: body
          description: Update informations about the transaction
          required: true
          schema:
            $ref: '#/definitions/EditDetails'
      produces:
        - application/json
      responses:
        '200':
          description: Details are successfully edited
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
          
    delete:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Delete informations about a transaction.
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: account_Id
          required: true
          type: integer
          description: Numeric ID of the account
        - in: path
          name: transaction_Id
          required: true
          type: integer
          description: Numeric ID of the transaction
      produces:
        - application/json
      responses:
        '200':
          description: Details are successfully deleted
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error


securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header


definitions:
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      id:
        type: string
        description: transaction id
  
  Transactions:
    type: array
    items:
      properties:
        id:
          type: integer
          description: transaction id
        date:
          type: string
          description: date of transaction
        description:
          type: string
          description: description of transaction
        amount:
          type: number
          description: transaction amount
        balance:
          type: number
          description: account balance
  
  TransactionDetails:
    type: object
    properties:
        id:
          type: integer
          description: transaction id
        transaction type:
          type: string
          description: transaction type
        category:
          type: string
          description: transaction category
        notes:
          type: string
          description: transaction notes
          
  EditDetails:
    type: object
    properties:
        category:
          type: string
          description: transaction category
        notes:
          type: string
          description: transaction notes
    
  